on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build React App
        run: npm run build
        env:
          CI: false
          
      - name: remove old file from EC2
        uses: appleboy/ssh-action@master
        if: contains(github.ref, 'develop')
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Remove old files from /var/www/html
            sudo rm -rf /var/www/html/*
            
      - name: scp to EC2
        uses: appleboy/scp-action@master
        if: contains(github.ref, 'develop')
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: client/build/*
          target: /var/www/html

      # - name: Add server to known_hosts
      #   run: |
      #     mkdir -p ~/.ssh
      #     ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      # - name: Deploy to Server
      #   uses: appleboy/ssh-action@master
      #   if: contains(github.ref, 'develop')
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       # Remove old files from /var/www/html
      #       sudo rm -rf /var/www/html/*
      #       # Copy new build files
      #       rsync -avz --delete -e "ssh -i ${{ secrets.SSH_KEY }} -o StrictHostKeyChecking=no" ./build/ ${{ secrets.SSH_USER }}@${{ secrets.HOST }}:/var/www/html/
